import Head from "next/head";
import { CalculatorTemplate } from "../templates/Calculator";

export default function Calculator() {
  return (
    <div>
      <Head>
        <title>Redux Next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CalculatorTemplate />
    </div>
  );
}
